<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.7.0 setup script
 * Date: Wed, 26 Apr 2017 06:26:42 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: junho [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'junho';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '"jz7Wg6iwiAFuO?V~c"MLGwz,{N-Bbv0';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>